# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing pm2...
      - npm install -g pm2
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - pm2 app.js
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# artifacts:
#   files:
#     - src/index.js
#     - src/app.js
#     - package.json
#     - node_modules/**/*
